let del;
del='<table><td id="lev">'
+'<a>Перегрузка операторов(продолжаем)</a><br>'
+'<li><i>Переопределение и перегрузка new и delete</i><br>'
+'<ul><i>Несколько причин для перегрузки этих операторов</i><br>'
+'<li type="disc" style="color:#ff4">Увеличение производительности за счёт кеширования: '
+'при удалении объекта не освобождать память, а сохранять указатели '
+'на сободные блоки.</li>'
+'<li type="disc"style="color:#f4f">Можно выделять память сразу под несколько объектов</li>'
+'<li type="disc"style="color:#4ff">Можно реализовать собственный "сборщик мусора"'
+'O(garbage collector).</li>'
+'<li type="disc"style="color:#4f4">Можно вести лог выделения/освобождения памяти</li>'
+'</ul><i>Сигнатуры у них следующие:</i><br>'
+'void *operator new(size_t size);<br>'
+'void operator delete(void *p);<br>'
+'class A{<br>'
+'	public:<br>'
		+'void *operator new(size_t size);<br>'
	+'	void operator delete(void *p);<br>'
+'};<br>'
+'void *A::operator new(size_t size){<br>'
	+'printf("Allocated %d bytes",size);<br>'
	+'return malloc(size);<br>'
+'}<br>'
+'void A::operator delete(void *p){<br>'
	+'free(p);<br>'
+'}<i>//ничего не выдал, но скомпилировался</i><br></li><li>'
+'<h4>Функции преобразования типа</h4>'
+'<ul style="margin-left:25px"><i>для неё действуют следующие правила:</i><br>'
+'<p><li type="square"style="color:#05a">функция преобразования не имеет параметров;</li>'
+'<li type="square"style="color:#00a">в функциях преобразования типа не задаётся тип возвращаемого '
+'значения(возвращает, указанный после слова operator)</li>'
+'<li type="square"style="color:#a50">функция преобразования типа наследуется</li>'
+'</p></ul><i>Будет что-то типа:</i><br>'
+'class Coord{<br>'
	+'int x,y;<br>'
+'   public:<br>'
     +'Coord(int _x, int _y){x=_x;y=_y;}<br>'
	+' operator int(){return x*y;}	<br>'
+'};<br>'
+'int main(){<br>'
	+'system("color 2f");<br>'
+'	setlocale(LC_ALL,"Rus");<br>'
	+'Coord Pt(10,20);<br>'
+'	int n;<br>'
	+'n=Pt+30;<br>'
+'	cout<<"int(Pt)= "&lt;&lt;int(Pt)&lt;&lt;endl;<br>'
	+'cout&lt;&lt;"n=Pt+30= "&lt;&lt;n;}<br>'
+'<i>//int(Pt)= 200<br>'
+'//n=Pt+30= 230</i><br></li>'
+'<ol><h3>Полиморфизм и виртуальные функции</h3>'
+'<li><a>Раннее и позднее связывание.<br>Динамический полиморфизм</a><br>'
+'<i>Функция вызывается только в момент выполнения. Память для неё зарезервирована, '
+'но остаётся свободной (позднее связывание). Вызванные объект сам определяет '
+'какая из функций должна работать.</i><br></li>'
+'<li><a>Виртуальные функции</a><br><i>Функции, вызов которых зависит от типа объекта, '
+'который выполнятеся в данное время, называются виртуальными. Это, так нызываемый, '
+'</i><i style="margin-left:0;font-family:oblique;font-size:13pt">динамический полиморфизм.</i></li>'
+'<li><a>Виртуальные функции</a><br>'
+'<i>В этом случае возможна реализация функций только в определённых случаях.</i><br>'
+'<i>Пример:</i><br>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'class Base{<br>'
   +'public:<br>'
   	+'Base(int _x){x=_x;}<br>'
   	+'virtual int GetX(){return x;}<br>'
   	+'virtual void PrintX();<br>'
   +'private:<br>'
  +'  int x;	};<br>'
+'void Base:: PrintX(){<br>'
	+'cout&lt;&lt;"Ошибка. Эта функция недоступна для Base.\n";}<br>'
+'class Derived1: public Base{<br>'
+'	public:<br>'
		+'Derived1(int _x): Base(_x){}<br>'
	+'	void PrintX();};<br>'
+'void<br>'
+'Derived1::PrintX(){<br>'
	+'cout&lt;&lt;"Derived1::x= "&lt;&lt;GetX()&lt;&lt;"\n";}<br>'
+'class Derived2: public Base{<br>'
+'	public:<br>'
		+'Derived2(int _x):Base(_x){}<br>'
	+'	void PrintX();};<br>'
+'void<br>'
+'Derived2:: PrintX(){<br>'
	+'cout&lt;&lt;"Derived2::x= "&lt;&lt;GetX()&lt;&lt;"\n";}<br>'
+'int main(){<br>'
+'	Derived1 *pDer1=new Derived1(10);<br>'
	+'Derived2 *pDer2=new Derived2(20);<br>'
+'	Base* pBase=pDer1;<br>'
	+'pBase->PrintX();<br>'
+'	pBase=pDer2;<br>'
	+'pBase->PrintX();<br>'
	+'return 0;<br>'
+'} <i>// Derived1:: x = 10<br>'
+'// Derived2:: x = 20</i><br>'
+'<ul><a>! </a><i style="margin:0">Когда вызывается функция при помощи указателей и ссылок, действуют правила:</i><br>'
+'<li type="square">Вызов виртуальной функции разрешается в соответствии с тем объектом '
+'для которого вызывается;</li><li type="square">Вызов виртуальной ссылки или '
+'указателя разрешается с его типом.</li></ul>'
+'&ensp;<div style="color:#444">Покажем, что виртуальная функция переопределяет только виртуальную функцию '
+'базового класса</div><br>'
+'#include<iostream><br>'
+'using namespace std;<br>'
+'class Base{<br>'
 +'    int x;<br>'
   +'public:<br>'
  +' 	virtual void SetValue(int _x){<br>'
+'   		x=_x;<br>'
   		+'cout&lt;&lt;"Base::x= "&lt;&lt;x&lt;&lt;"\n";}<br>'
   	+'virtual void Show(Base* p0b)<br>'
  +' 	   {SetValue(10);}};<br>'
+'class Derived: public Base{<br>'
	+'int x,y;<br>'
  +' public:<br>'
+'     virtual void SetValue(int _x,int _y){<br>'
     +'	x=_x;y=_y;<br>'
    +' 	cout<<"Derived::x= "&lt;&lt;x&lt;&lt;" Derived::y= "&lt;&lt;y&lt;&lt;"\n";}<br>' 	
  +'   void Show(Base* p0b){SetValue(15,20);}};<br>'
+'int main(){<br>'
	+'Base* p0b1=new Base;<br>'
+'	Base* p0b2=new Derived;<br>'
	+'<i>//virtual function Show()<-Base</i><br>'
+'	p0b1->Show(p0b1);<br>'
	+'<i>//virtual function Show()<-Derived</i><br>'
+'	p0b2->Show(p0b1);<br>'
	+'<i>//...</i><br>'
+'	p0b2->Show(p0b2);<br>'
	+'return 0;<br>'
+'} <i>//Base::x= 10<br>'
+'//Derived::x= 15 Derived::y= 20<br>'
+'//Derived::x= 15 Derived::y= 20</i><br></ul>'
+'</li>'
+'<li><a>Виртуальные и невиртуальные функции</a><br>'
+'<i>Вызываем их через указатели:</i><br>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'class Base{<br>'
+'	public:<br>'
		+'virtual void VirtFunc();<br>'
	+'	void InvokingClass();};<br>'
+'void<br>'
+'Base:: VirtFunc(){<br>'
	+'cout&lt;&lt;"Base:: VirtFunc()\n";}<br><br>'
+'void<br>'
+'Base::InvokingClass(){<br>'
	+'cout&lt;&lt;"Функция вызывана классом Base\n";}<br>'
+'class Derived: public Base{<br>'
+'	public:<br>'
	+'	<i>//virt function</i><br>'
+'		void VirtFunc();<br>'
		+'<i>//antivirt function</i><br>'
	+'	void InvokingClass();};<br><br>'
+'void<br>'
+'Derived:: VirtFunc(){<br>'
	+'cout&lt;&lt;"Derikved:: VirtFunc()\n";}<br><br>'
+'void<br>'
+'Derived::InvokingClass(){<br>'
	+'cout&lt;&lt;"Функция вызвана классом Derived\n";}<br><br>'
+'&ensp;int main(){<br>'
	+'setlocale(LC_ALL,"Rus");<br>'
+'	Derived aDerived;<br>'
	+'Derived *pDerived=&aDerived;<br>'
+'	Base    *pBase=&aDerived;<br>'
	+'<i>//virt function</i><br>'
+'	pBase->VirtFunc();<br>'
	+'<i>//antyvirt// function</i><br>'
+'	pBase->InvokingClass();<br>'
	+'<i>//virt function</i><br>'
+'	pDerived->VirtFunc();<br>'
	+'<i>//antyvirt// function</i><br>'
+'	pDerived->InvokingClass();<br>'
	+'return 0;<br>'
+'} <i>//Derived:: VirtFunc()<br>'
+'//Функция вызвана классом Base<br>'
+'//Derived:: VirtFunc()<br>'
+'//Функция вызвана классом Derived</i><br></li><li>'
+'<a style="margin:0cm">Разница между виртуальной и невиртуальной функцией</a><br>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'class Base{<br>'
	+'public:<br>'
+'		virtual void VirtFunc(){<br>'
			+'cout&lt;<"Мы в Base::VirtFunc\n";}<br>'
		+'void NonVirtFunc(){<br>'
	+'		cout&lt;<"Мы в Base::NonVirtFunc\n";};<br>'
+'<i>//Производный класс переопределяет функции класса Base</i><br>'
+'class Derived: public Base{<br>'
+'	public:<br>'
	+'	virtual void VirtFunc(){<br>'
+'			cout&lt;<"Мы в Derived::VirtFunc\n";}<br>'
		+'void NonVirtFunc(){<br>'
	+'		cout&lt;<"Мы в Derived::NonVirtFunc\n";}	};<br>'
+'int main(){<br>'
	+'setlocale(LC_ALL,"Rus");<br>'
+'	Base* pBase=new Derived;<br>'
	+'<i>//вызов виртуальной функции из Derived</i><br>'
+'	pBase->VirtFunc();<br>'
	+'<i>//Вызов невиртуальной функции из Base</i><br>'
+'	pBase->NonVirtFunc();<br>'
	+'return 0;<br>'
+'} <i>//Мы в Derived::VirtFunc<br>'
+'//Мы в Base::NonVirtFunc</i><br>'
+'<div style="color:#424;margin-left:10pt">Использование оператора расширения области видимости'
+' <b style="margin:0">(::)</b></div><br>'
+'&ensp;#include&lt;iostream><br>'
+'using namespace std;<br>'
+'&ensp;class Base{<br>'
+'	public:<br>'
		+'virtual void VirtFunc(){<br>'
	+'		cout&lt;<"Мы в Base::VirtFunc\n";}};<br>'
+'&ensp;class Derived: public Base{<br>'
+'	public:<br>'
		+'virtual void VirtFunc(){<br>'
	+'		cout&lt;<"Мы в Derived::VirtFunc\n";}};<br>'
+'int main(){<br>'
+'	&ensp;setlocale(LC_ALL,"Rus");<br>'
	+'Base* pBase=new Derived;<br>'
+'	<i>//вызов виртуальной функции из Derived</i><br>'
	+'pBase->VirtFunc();<br>'
+'	<i>//вызов невиртуальной функции из Base<br>'
	+'//механизм позднего связывания включён</i><br>'
+'	pBase->Base::VirtFunc(); <i>//она виновата</i><br>'
	+'return 0;<br>'
+'} <i>//Мы в Derived::VirtFunc<br>'
+'//Мы в Base::VirtFunc</i><br>'
+'<a>Могут иметь место совпадения имён виртуальных функций с невиртуальными. В этом случае '
+'имена невиртуальных функций оказываются скрытыми</a><br>'
+'#include&lt;iostream><br>'
+'#include&lt;cstring><br>'
+'using namespace std;<br>'
+'class Base{<br>'
+'	public:<br>'
	+'  Base(char* name){strcpy(Name,name);}<br>'
+'	  virtual void Func(char c){<br>'
	  +'	cout&lt;&lt;"virtual "&lt;&lt;Name&lt;&lt;"::Func "&lt;&lt;" принимает параметр "&lt;&lt;c&lt;&lt;endl;}<br>'	
	+'  protected:<br>'
+'	  	char Name[20];};<br>'
		+'class Derived1: public Base{<br>'
	+'		public:<br>'
+'				Derived1(char* name):Base(name){}<br>'
				+'void Func(const char* s){<br>'
			+'		cout&lt;&lt;Name&lt;&lt;" ::Func "&lt;&lt;"принимает параметр "&lt;&lt;s&lt;&lt;endl;}<br>'
		+'		void Func(int n){<br>'
	+'				cout&lt;&lt;Name&lt;&lt;" ::Func"&lt;&lt;" принимает параметр "&lt;&lt;n&lt;&lt;endl;}<br>'
+'				virtual void Func(char c){<br>'
					+'cout<<"virtual "&lt;&lt;Name&lt;&lt;" ::Func"<br>'
				+'	<<" принимает параметр "&lt;&lt;c&lt;&lt;endl;}};<br>'
			+'			class Derived2: public Derived1{<br>'
		+'				public:<br>'
	+'						Derived2(char* name):Derived1(name){}<br>'
+'							void Func(const char* s){<br>'
								+'cout&lt;&lt;Name&lt;&lt;" ::Func"&lt;&lt;" принимает параметр "<br>'
							+'	&lt;&lt;s&lt;&lt;endl;}<br>'
						+'	void Func(double d){<br>'
					+'			cout&lt;&lt;Name&lt;<" ::Func "<br>'
				+'				<<" принимает параметр "&lt;&lt;d&lt;&lt;endl;}<br>'
			+'					virtual void Func(char c){<br>'
		+'							cout&lt;<"virtual "&lt;&lt;Name&lt;<"::Func"<br>'
	+'								&lt;<" принмает параметр "&lt;&lt;c&lt;&lt;endl;}	};<br>'
+'int main(){<br>'
+'	setlocale(LC_ALL,"Rus");<br>'
	+'Base base("Base");<br>'
+'	Derived1 der1("Derived1");<br>'
	+'Derived2 der2("Derived2");<br>'
+'	base.Func(&lsquo;X&rsquo;);<br>'
	+'der1.Func(&lsquo;Y&rsquo;);<br>'
+'	der1.Func(10);<br>'
	+'der1.Func("Der1");<br>'
+'	der2.Func(&lsquo;z&rsquo;);<br>'
	+'der2.Func(10.1234);<br>'
+'	der2.Func("Der2");<br>'
	+'return 0;<br>'
+'} <i>//virtual Basse::Func принимает параметр X<br>'
+'virtual Derived1 ::Func принимает параметр Y<br>'
+'Derived1 ::Func принимает параметр 10<br>'
+'Derived1 ::Func принимает параметр Der1<br>'
+'virtual Derived2::Func принимает параметр z<br>'
+'Derived2 ::Func  принимает параметр 10.1234<br>'
+'Derived2 ::Func принимает параметр Der2</i><br></li>'
+'<li><a>Применение динамического полиморфизма</a><br>'
+'<i>Для примера расмотрим иерархию классов</i><br>'
+'#include<iostream><br>'
+'#include<cctype><br>'
+'#include<cstdlib><br>'
+'using namespace std;<br>'
+'<i>//абстрактный класс для списков</i><br>'
+'class List{<br>'
+'	public:<br>'
		+'List(){Head = Tail = Next = 0;}<br>'
	+'	virtual void Put(int n)=0;<br>'
+'		virtual bool Get(int& n)=0;<br>'
		   +'void SetValue(int n){Num = n;}<br>'
		  +' int GetValue(){return Num;}<br>'
		+'   <i>//указатель на начало списка</i><br>'
	+'	   List* Head;<br>'
+'		List* Tail; <i>//Указатель на конец списка</i><br>'
		+'List* Next;<i> //указатель на следующий элемент списка</i><br>'
	+'private:<br>'
	+'int Num;	   };<br>'
+'<i>//список типа "очередь"</i><br>'
+'class Queue: public List{<br>'
+'	public:<br>'
		+'void Put(int n);<br>'
	+'	bool Get(int& n);};<br>'
+'void<br>'
+'Queue::Put(int n){<br>'
	+'List* Item;<br>'
+'	<i>//создание нового элемента очереди</i><br>'
	  +' Item = new Queue;<br>'
	+'   <i>//восстанавливаем хранимое значение</i><br>'
+'	   Item->SetValue(n);<br>'
	 +'<i>  //добавляем в конец очереди</i><br>'
	+'   if(Tail)Tail->Next = Item;<br>'
+'	   Tail=Item;<br>'
	  +' Item->Next = NULL;<br>'
	+'   if(!Head) Head = Tail;}<br>'
+'bool<br>'
+'Queue::Get(int& n){<br>'
	+'List* Item;<br>'
+'if(!Head){<br>'
+'	n=0;<br>'
	+'return false;}<br>'	
+'<i>//устанавливаем значение первого элемента очереди</i><br>'
+'n=Head->GetValue();<br>'
+'<i>//устанавливаем начало очереди на следующий элемент</i><br>'
+'Item = Head;<br>'
+'Head = Head->Next;<br>'
+'<i>//первый элемент очереди</i><br>'
+'delete Item;<br>'
+'return true;}<br>'
+'<i>//список типа "стек"</i><br>'
+'class Stack: public List{<br>'
+'	public:<br>'
		+'void Put(int n);<br>'
	+'	bool Get(int& n);};<br>'
+'void<br>'
+'Stack::Put(int n){<br>'
+'	List* Item;<br>'
	+'<i>//new element stek</i><br>'
+'	Item = new Stack;<br>'
	   +'<i>//устанавливаем хранимое значение</i><br>'
	  +' Item->SetValue(n);<br>'
	+'   <i>//new Element in start</i><br>'
+'	   if(Head) Item->Next = Head;<br>'
	  +' Head = Item;<br>'
	+'   if(!Tail) Tail=Head;}<br>'
+'bool<br>'
+'Stack::Get(int& n){<br>'
	+'List* Item;<br>'
+'	if(!Head){<br>'
		+'n=0;<br>'
	+'	return false;}<br>'
+'	<i>//устанавливаем значение первого элемента стека</i><br>'
	+'n = Head->GetValue();<br>'
+'	<i>//устанавливаем начало стека на следующий элемент</i><br>'
	+'Item = Head;<br>'
+'	Head = Head->Next;<br>'
	+'<i>//удаление первого элемента стека</i><br>'
+'	delete Item;<br>'
	+'return true;}<br>'
+'int main(){<br>'
+'	setlocale(LC_ALL,"Rus");<br>'
	+'List* Item;<br>'
+'	int saved;<br>'
	+'Queue QueOb;<br>'
+'	Stack StOb;<br>'
	+'char symbol;<br>'
+'	for(int i=0;i<10;i++){<br>'
	+'	cout<<"Куда поместить значение, в очередь или стек?(): ";<br>'
+'		   cin>>symbol;<br>'
		+'symbol = tolower(symbol);<br>'
	+'	if(symbol == &lsquo; o &lsquo;) Item = &QueOb;<br>'
+'		else if(symbol == &lsquo; c &lsquo;) Item = &StOb;<br>'
		+'else break;<br>'
	+'	Item->Put(i);   }<br>'
+'	cout&lt;&lt;"Откуда извлечь значение? (О&#47;С)\n Нажмите <К>,"<br>'
	+'<< "чтобы завершить работу\n";<br>'
+'	for(;;){<br>'
	+'	cin>>symbol;<br>'
+'		symbol = tolower(symbol);<br>'
		+'if(symbol == &lsquo; k &lsquo;)<br>'
	+'	   break;<br>'
+'		if(symbol == &lt;o&lt;) Item = &QueOb;<br>'
		+'else if(symbol == &lsquo; c &lsquo;) Item = &StOb;<br>'
	+'	else break;<br>'
+'		if(Item->Get(saved))<br>'
		  +' cout&lt;&lt;saved<<"\n";<br>'
		+'else<br>'
	+'	cout<<"Spisok pust\n";      }<br>'
+'	return 0;} <i>//зачем программа, я не понял. Но работает</i><br>'

+'</li>'
+'<br><li><ul><a>Виртуальные деструкторы</a> <i>действуют правила:</i><br>'
+'<li type="square">используйте виртуальный деструктор, если в базовом классе '
+'имеются виртуальные функции;</li>'
+'<li type="square">используйте виртуальные функции только в том случае, если программа '
+'содержит и базовый, и производный классы;</li>'
+'<li type="square">не птайтесь создать виртуальный конструктор(опасно).</li>'
+'<br><li><a>Абстрактные классы и чисто виртуальные функции</a><br>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'class Account{<br>'
+'&ensp;	public:<br>'
	+'&ensp;&ensp;	Account( double d){_balance = d;}<br>'
+'&ensp;&ensp;		virtual ~Account(){}<br>'
		+'&ensp;&ensp;virtual double GetBalance(){return _balance;}<br>'
	+'&ensp;&ensp;	virtual void PrintBalance(){cerr << "Error. Not available for base type"<<endl;}<br>'
+'&ensp;	private:<br>'
	+'  &ensp;&ensp; double _balance;	};<br>'
+'class CheckingAccount : public Account{<br>'
+'&ensp;	public:<br>'
		+'&ensp;&ensp;CheckingAccount(double d): Account(d){}<br>'
	+'&ensp;&ensp;	void PrintBalance(){cout<<"Checking account balance"<<GetBalance()<<endl;}};<br>'	
+'class SavingsAccount	: public Account{<br>'
+'public:<br>'
 +' &ensp; SavingsAccount(double d) : Account(d){}<br>'
  +'&ensp; void PrintBalance(){cout<<"Saving account balance: "<<GetBalance();}	};<br>'
+'int main(){<br>'
	+'&ensp;setlocale(LC_ALL,"Rus");<br>'
+'	<i>//создать объекты по типам</i><br>'
	+'&ensp;CheckingAccount checking(100.00);<br>'
+'&ensp;	SavingsAccount savings(1000.00);<br>'
	+'<i>//вызывать объект, используя указатель</i><br>'
+'&ensp;	Account *pAccount=&checking;<br>'
	+'&ensp;pAccount->PrintBalance();<br>'
+'	<i>//повторяем операцию</i><br>'
	+'&ensp;&ensp;pAccount = &savings;<br>'
+'&ensp;	pAccount->PrintBalance();<br>'
	+'<i>//return 0;</i><br>'
+'} <i>//Checking account balance100<br>'
+'  //Saving account balance: 1000</i><br></li><li>'
+'<ul><i style="color:#0a6">Есть правила при вызове функций с помощью указателей:</i><br>'
+'<li type="disc">Вызов виртаульной функции разрешается только в соответствие '
+'с бозовым типом объекта для которого вызывается</li>'
+'<li type="disc">вызов невиртуальной функции возмложен только при соответствие '
+'с типом указателя иди ссылки. </li></ul>'
+'<i>Пример:</i><br>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'class Base{<br>'
+'&ensp;	public:<br>'
		+'&ensp;&ensp;virtual void NameOf(); <i>//virtual function</i><br>'
	+'&ensp;	void InvokingClass(); <i>//Nonvirtual function};</i><br>'
+'<i>//Implement the two functions</i><br>'
+'void Base::NameOf(){<br>'
	+'&ensp;cout<<"Base::nameOf\n";}<br>'
+'void Base::InvokingClass(){<br>'
+'cout<<"Invoked by Base\n";}<br>'
+'class Derived : public Base{<br>'
+'	&ensp;public:<br>'
	+'&ensp;&ensp;	void NameOf(); <i>//Virtual function</i><br>'
+'&ensp;&ensp;		void InvokingClass(); <i>//Nonvirtual function.};</i><br>'
+'<i>//Implement the two functions.</i><br>'
+'void Derived::NameOf(){<br>'
	+'&ensp;cout<<"Derived::NameOf\n";}<br>'
+'void Derived::InvokingClass(){<br>'
  +'&ensp; cout<<"Invoked by Derived\n";}<br>'
+'<div style="color:green">int main()</div>{<br>'
	+'&ensp;setlocale(LC_ALL,"Rus");<br>'
+'	<i>//declare an object of type derived.</i><br>'
	+'Derived aDerived;<br>'
+'	<i>//Delare two pointers, one type Derived * and the other<br>'
	+'//of type Base *, and initialize them to point to aDerived.</i><br>'
+'	Derived *pDerived=&aDerived;<br>'
	+'Base *pBase=&aDerived;<br>'
+'	<i>// Call the functions.</i><br>'
	+'pBase->NameOf(); //Call virtual function</i><br>'
+'	pBase->InvokingClass(); //Call nonvirtual function</i><br>'
	+'pDerived->NameOf(); //Call virtual function</i><br>'
+'	pDerived->InvokingClass(); //Call nonvirtual function</i><br>'
	+'return 0;<br>'
+'} <i>/*Derived::NameOf<br>'
+'Invoked by Base<br>'
+'Derived::NameOf<br>'
+'Invoked by Derived*/ </i><br>'
+'</li></ul></li></ol>'
+'</td><td id="prav">'
+'<ul><h3>Исключения и информация о типе времени выполнения</h3><br>'
+'<li type="square"><a>Обработка исключительных ситуаций</a><br>'
+'<i>Исключение - </i>неожиданное событие, которое прерывает '
+'нормальный процесс.<br>'
+'&ensp;try<br>{&ensp;<i style="margin-left:0">//защищённый блок кода&ensp;</i>}<br>'
+'&ensp;за блоком следует ключевое слово <i style="margin-left:0">catch</i><br>'
+'catch(<тип_искл> <пер_искл>){<br>'
+'&ensp;<i>/*Обработчик исключения*/</i><br>}<br>'
+'<i style="font-size:16px">Простой пример обработки исключения:</i><br>'
+'#inclue<exception><br>'
+'#inclue<iostream><br>'
+'using std::cout;<br>'
+'void func()&ensp;{<br>&ensp;<i>//функция герерирует исключение</i><br>{<br>'
+'int main(){<br>&ensp;try{<br>'
+'<i>//Пример использования механизма обработки исключений C++</i><br>'
+'func();<br>return 0;<br>}<br>'
+'catch (const char*){<br>'
+'<i>//Обработчик исключения типа const char*</i><br>'
+'cout<<"Было выбрашено исключение типа const char*\n";<br>'
+'return 1;<br>}<br>'
+'catch (...){<br>'
+'<i>//Обработчик всех необработанных исключений</i><br>'
+'cout<<"Было выброшено исключение типа другого типа\n";<br>'
+'reurn 1;<br>'
+'}}<br></li>'
+'<li type="square"><a>Генерирование исключений</a><br>'
+'Его синтаксис: throw <выраж>;<i> значение, которое инициализирует врменный объект</i><br>'
+'<i>Демонстрация вбрасывания исключений:</i><br>'
+'#include&lt;cstdio><br>'
+'using namespace std;<br>'
+'bool test;<br>'
+'class SomeException{};<br>'
+'void Func(bool bvar){<br>'
	+'if(bvar)throw SomeException();}<br>'
+'int main(){<br>'
+'	setlocale(LC_ALL,"Rus");<br>'
   +'try{<br>'
  +' 	test=true;<br>'
   	+'Func(true);}<br>'
  +' catch(SomeException& e){<br>'
   	+'test=false;}<br>'
  +' return test ? (puts("test = true.\n"),1):<br>'
  +' 	             (puts("test = false.\n"),0);<br>'
+'} <i>//test = false.(очень логично и понятно)</i><br></li>'
+'<li type="square"><a>Создание объекта исключения</a><br>'
+'<i>для экономии памяти объекты для проверки передаются обычно по ссылке:</i><br>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'double divide(int a,int b){<br>'
	+'if(b)<br>'
	  +' return a/b;<br>'
	+'   throw string{"Division by zero!"};}<br>'
+'int main(){<br>'
	+'setlocale(LC_ALL,"Rus");<br>'
	+'int x{500};<br>'
	+'int y{};<br>'
	+'try{<br>'
		+'double z{divide(x, y)};<br>'
		+'cout&lt;&lt;z&lt;&lt;endl;}<br>'
	+'catch(const string& error_message){ <i>//передаётся по ссылке</i><br>'
	  +' cout&lt;&lt;error_message&lt;&lt;endl;	}<br>'
	+'cout&lt;&lt;"The End..."&lt;&lt;endl;<br>'
+'} <i>//Division by zero!<br>'
+'//The End...</i><br></li>'
+'<li type="square"><a>обработка и генерация разных типов исключений</a><br>'
+'<i>Исключений может быть несколько</i><br>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'double divide(int a,int b){<br>'
+'	if(!b){ <i>//если b==0</i><br>'
	+'   throw 0;} <br>'
+'	if(b>a){<br>'
		+'throw "The second number is greater than the first one";}<br>'
	+'return a/b;}<br>'
+'void test(int a,int b){<br>'
+'	try{<br>'
		+'double result{divide(a,b)};<br>'
	+'	cout&lt;&lt;result&lt;&lt;endl;}<br>'
+'	catch(int code){<br>'
	+'	cout&lt;&lt;"Error code: "&lt;&lt;code&lt;&lt;endl;}}<br>'
+'int main(){<br>'
+'	setlocale(LC_ALL,"Rus");<br>'
	+'test(100,20);<br>'
+'	test(100,0);<br>'
	+'test(100,1000); <br>'
+'} <i>//5 (верно)<br>'
+'//Error code: 0 (на ноль делить нельзя)<br>'
+'//terminate called after throwing an instance of "char const*"</i><a style="margin-left:10px">(</a>какой-то '
+'строковый литерал. Я не понял зачем это.<a style="margin-left:5px">)</a><i style="margin:0"> Делитель больше делимого</i></li><li><br>'
+'<figure class="right"><a><figcaption  style="margin-top:70px" class="right">try-catch и деструкторы</figcaption>'
+'<img src="https://i.postimg.cc/PJkkPG38/logoC.png" width="200"></a></figure><br>'
+'<i style="margin-left:5px">если в блоке try создаются объекты, то при наличии исключений у них создаются '
+'дуструкторы.</i><br> <a>Пример:</a><br>'
+'<i>#include&lt;iostream></i><br>'
+'using namespace std;<br>'
+'class Person{<br>'
	+'&ensp;public:<br>'
+'		&ensp;&ensp;Person(string name) :name{name}{<br>'
		  +' &ensp;&ensp;cout&lt;&lt;"Person "&lt;&lt;name&lt;&lt;" created"&lt;&lt;endl;}<br>'
		+'&ensp;~Person(){<br>'
	+'		&ensp;cout<<"Person "&lt;&lt;name&lt;&lt;" deleted"&lt;&lt;endl;}<br>'
+'	<i>	void print()</i>{<br>'
		+'&ensp;&ensp;	throw "Print Error";}<br>'
		+'private:<br>'
	+'&ensp;		string name;};<br>'
+'<i>int main()</i>{<br>'
	+'&ensp;setlocale(LC_ALL,"Rus");<br>'
+'  try{<br>'
  +'Person tom("Tom");<br>'
+'  tom.print(); <i>//hier error}</i><br>'
  +'catch(const char* error){<br>'
+'  	&ensp;cerr&lt;&lt;error&lt;&lt;endl;} <br>'
	+'}<i>//Person Tom created<br>'
+'//Person Tom deleted<br>'
+'//Print Error</i><br><li><li></li></ul>'
+'<ul style="margin-left:10px"><h4>Перехватывание исключений</h4>'
+'при обнаружении исключения поток программы прерывается и начинается:<br>'
+'<li type="square">Если выброшена переменная встроенного типа, то создаётся её копия. '
+'Если выброшена переменная по ссылке, то копирования не происходит;</li>'
+'<li type="square">Происходит поиск ближайшего обработчика, чтобы принять параметр, '
+'который совместим по типу с выбрашенной переменной;</li>'
+'<li type="square">При нахождении обработчика, до нужных размеров удляняется стек и '
+'вызываются деструкторы, которые выходят из области видимости;</li>'
+'<li type="square">Управление программой переходит к найденному обработчику;</li>'
+'<li type="square">Вдруг обработчик не найдёте, всегда можете вызывать '
+'set_terminate(), предоставив обработчик завершения вручную; иначе программа '
+'сделает всё сама.</li>'
+'<a>И тут компилятор начинает чудить. Но обработчик считается найденным если: </a><br>'
+'<li type="square">тип выброшенной переменной совпадает с типом, который ожидает сам '
+'обработчик. Если тип переменной T, то соответствуют ему обработчики типа T, condtT.'
+'T& и const T&;</li>'
+'<li type="square">тип выброшенной переменной представляет собой указатель, тип '
+'которого может быть преобразован к типу, который перехватывает обработчик;</li>'
+'<li type="square">если выброщенная переменная представляет собой объект некоторого '
+'класса, а тип исключения является базовым классом, наследуемым этим объектом '
+'как public.<br><br>'
+'<i>Небольшой пример из обработчиков, указателей, исключений и т.д. </i><br>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'class Base{}; <br>'
+'class Derived : public Base{};<br>'
+'void FuncExDerived(){<br>'
+'	&ensp;Derived derOb;<br>'
	+'&ensp;throw derOb;}<br>'
+'void FuncExErr(){<br>'
	+'&ensp;throw "ошибка функции FuncExErr()";}<br>'
+'<i>int main()</i>{<br>'
	+'&ensp;setlocale(LC_ALL,"Rus");<br>'
 +' try{<br>'
 +' &ensp;	FuncExDerived();}<br>'
 +' catch(Derived&){<br>'
 +' 	&ensp;cout&lt;<"исключение перехвачено в Derived&"<&lt;endl;}<br>'
  	+'<i>//обработчик скрывает предыдущий</i><br>'
 +' &ensp;	catch(Base&){<br>'
  	+'	&ensp;cout&lt;<"исключение перехвачено в Base&"<&lt;endl;}<br>'
 +' 	&ensp;try{<br>'
  	+'	&ensp;FuncExErr();}<br>'
 +' 	&ensp;catch(const char*){<br>'
  	+'	&ensp;cout&lt;<"исключение перехвачено в const char*"<&lt;endl;}<br>'
  +'	<i>//обработчик скрывает предыдущий</i><br>'
+'  	&ensp;catch(void*){<br>'
  		+'&ensp;cout&lt;<"исключение перехвачено в void*"<&lt;endl;}<br>'
	+'  return 0;}<br>'
+'<i>//Исключение перехвачено в Derived&<br>'
+'//исключение перехвачено в const char*</i><br></li><hr><li>'
+'<a>Использование вложенных блоков try/catch</a><br>'
+'<i>За каждым try-блоком должен следовать catch-блок</i><br>'
+'<center><img src="https://i.postimg.cc/44WQbjLN/try.png" width="400" height="250">'
+'<br>Типа пример кода:</center>'
+'#include&lt;iostream><br>'
+'using namespace std;<br>'
+'class Base{};<br>'
+'class Derived : public Base{};<br>'
+'void FuncExDerived(){<br>'
+'	Derived derOb;<br>'
	+'throw derOb;}<br>'
+'int main(){<br>'
	+'setlocale(LC_ALL,"Rus");<br>'
 +'try{<br>'
 	+'<i>//...</i><br>'
 +'	try{<br>'
 	+'	FuncExDerived();<br>'
 +'	}catch(Derived&){<br>'
 		+'cout&lt;<"Исключение перехвачено в Derived&"<&lt;endl;}<br>'
 	+'<i>//...</i><br>'
 +'	Base baseOb;<br>'
+' 	<i>//...</i><br>'
 	+'throw baseOb;}<br>'
 +'catch(Base&){<br>'
 +'	cout&lt;<"Исключение перхвачено в Base&"<&lt;endl;}<br>'
	+'  return 0;<br>'
+'}<i>//Исключение перехвачено в Derived&<br>'
+'//Исключение перехвачено в Base&</i><br></li><br><li>'
+'<a>Неожиданные исключения и обработка завершения</a><br>'
+'К таким исключениям относят функцию <b style="margin:0">unexpected()</b>. Вызывает обработчик '
+'неожиданных исключений, функцию <b style="margin:0">terminate()</b>.<br>'
+'<i>Прототип: </i>void unexpected();<br>'
+'<i>Собственный обработчик(прототип): </i><br>'
+'unexpected_handler<br>set_unexpected<br>'
+'<div margin-left="40cm">(unexpected_handler ph) throw();<br>'
+'<i>Тут описывается указатель на обработчик неожиданных исключений:</i><br>'
+'typedef void(*une[pected_handler)();<br>Не может быть нулевым, так как '
+'на что-то указывает в любом случае.</div>'
+'<ul><i>Программа завершается следующим образом:</i><br>'
+'<li type="square">выбросив исключение типа, предусмотренного в спецификации '
+'исключений функции, вызвавшей появления неожиданности;</lu>'
+'<li type="square">выброси исключение типа bad_expection;</lu>'
+'<li type="square">вызывает одну из функций terinate(), abort() или exit().</lu></ul>'
+'<i>Класс exception объявлен следующим образом:</i><br>'
+'class exception<br>{<br>&nbsp;public:<br>&ensp;'
+'&ensp;exception() throw();<br>'
+'&ensp;exception(const exception& rhs) throw();<br>'
+'&ensp;exception& operator = (const exception& rhs) throe();<br>'
+'&ensp;virtual ~exception() throw();<br>'
+'&ensp;virtual const char *what() const throw();<br>};<br>'
+' <i style="color:green">Пример обработки неожиданных исключений: </i><br>'
+'#include&lt;iostream><br>'
+'#include&lt;exception><br>'
+'using namespace std;<br>'
+'<i>//функция не должна выбрасывать исключения</i><br>'
+'void f() throw(){<br>'
+'<i>//неожиданный выброс исключения приводит к вызову unexpected()</i><br>'
+'throw "bad";}<br>'
+'void My_unexp_handler(){<br>'
 +'exit(-1); <i>//на этой строке код перестаёт выполняться}</i><br>'
+'int main(){<br>'
+'   setlocale(LC_ALL,"rus");<br>'
  +' set_unexpected(My_unexp_handler);<br>'
+'   f();<br>'
  +' cout<<"Эта строка кода никогда не доcтигается";<br>'
+'   return 0;}<br>'
+'<i>После этого очищается память и вызываетсчя функция exit()<br>'
+'<br><div style="color:#333">Ещё один, мать его, пример:</div></i>'
+'#include&lt;iostream><br>'
+'#include&lt;exception><br>'
+'using namespace std;<br>'
+'void My_term_func();<br>'
+'int main(){<br>'
	+'setlocale(LC_ALL,"Rus");<br>'
+'	int i=10,j=0,res;<br>'
	+'set_terminate(My_term_func);<br>'
+'	try{<br>'
		+'if(j==0) throw "Делениие на ноль"; <i>//уже ошибка</i><br>'
	+'	else res = i/j;}<br>'
+'	catch(int){<br>'
		+'cout<<"Перехватывает некоторое исключение типа integer.\n";}<br>'
	+'cout<<"Эта строка никогда не будет напечатана\n";}<br>'
+'void My_term_func(){<br>'
	+'cout<<"My_term_func() была вызвана функцией terminate().\n";<br>'
+'	<i>//Выполняется очистка памяти и другие действия</i>	<br>'
	+'exit(-1);<br>'
+'} <i>//просто с ошибкой завершается</i><br></li><li>'
+'<a>Исключения и конструкторы</a><br>'
+'<div style="color:#044">Если конструктор класса не может соорудить объект, то он выбрасывает исключение</div><br>'
+'#include&lt;iostream><br>'
+'#include&lt;exception><br>'
+'using namespace std;<br>'
+'class Data{<br>'
	+'public:<br>'
+'		Data(){cout<<"Data::Data()\n"<br>'
		+'<<"Throw exeption\n";throw "Error.";}<br>'
	+'	~Data(){cout<<"Data::~Data()\n";}};<br>'
+'class Base{<br>'
+'	public:<br>'
		+'Base(){cout<<"Base::Base\n";}<br>'
	+'	~Base(){cout<<"Base::~Base\n";}};<br>'
+'class Derived: public Base{<br>'
	  +' Data data;<br>'
	+'public:<br>'
	  +' Derived(){cout<<"Derived::Derived()\n";}<br>'   
	+'   ~Derived(){cout<<"Derived::~Derived\n";}	};<br>'
+'int main(){<br>'
	+'setlocale(LC_ALL,"Rus");<br>'
+'   try{<br>'
  +' 	Derived derOb;<br>'
+'   	//...}    <br>'
   +'catch(const char* s){<br>'
  +' 	cout<<s<<"\n";}<br>'
+'return 0;<br>'
+'}<div style="color:#880">Base::Base<br>'
+'Data::Data()<br>'
+'Throw exeption<br>'
+'Base::~Base<br>'
+'Error.</div><br>'


+'</li></ul>'
+'</td><table>'

document.write(del);